# docker-compose.prod.yml
version: '3.8'

services:
  api:
    image: ghcr.io/make-kyiv-great-again/svitliachok-backend:latest
    container_name: svitliachok_api_prod
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
      - proxy-network

  db:
    image: pgrouting/pgrouting:latest
    container_name: svitliachok_db_prod
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: svitliachok
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  pgdata_prod:

networks:
  proxy-network:
    external: true